version: '3'

name: def-test

services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - "8080:8080"
    command: ["app"]

  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    command: ["app", "--host=host.docker.internal:8080"]

  jsclient:
    build:
      context: .
      dockerfile: ./cmd/js-client/Dockerfile
    command: ["node", "index.mjs", "bin", "host.docker.internal:8080"]

